/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      #score_threshold: 2.0
      score_threshold: 5.0 
      #ndt_resolution: 1.0
      ndt_resolution: 1.0
      #ndt_step_size: 0.1
      ndt_step_size: 0.1
      ndt_num_threads: 4
      #transform_epsilon: 0.01
      transform_epsilon: 0.01
      #voxel_leaf_size: 0.2
      voxel_leaf_size: 0.1
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      #map_path: "/home/shugo/pcd/5th_ex_outdoor.pcd"
      # map_path: "/home/shugo/pcd/20231208_edit.pcd"
      map_path: "/home/shugo/pcd/rinpukan_0314.pcd"

      set_initial_pose: true
#5th_ex_indoor
      # initial_pose_x: 0.0
      # initial_pose_y: 0.0
      # initial_pose_z: 0.0
      # initial_pose_qx: 0.0
      # initial_pose_qy: 0.0
      # initial_pose_qz: 0.921
      # initial_pose_qw: 0.387

#5th_ex_outdoor
      # initial_pose_x: -6.38
      # initial_pose_y: 6.85
      # initial_pose_z: 0.0
      # initial_pose_qx: 0.0
      # initial_pose_qy: 0.0
      # initial_pose_qz: -0.397
      # initial_pose_qw: 0.918


#rinpukan
      initial_pose_x: 37.578
      initial_pose_y: 6.369
      initial_pose_z: 3.377
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.78021
      initial_pose_qw: 0.625

      use_odom: true
      use_imu: false
      enable_debug: false
      global_frame_id: "map"
      odom_frame_id: "map"
      base_frame_id: "base_link"
